// this file is generated by src/scripts/watcher.effect.ts
import Form from "@/registry/new-york/blocks/basic-info";
import { createFileRoute } from "@tanstack/react-router";
export const Route = createFileRoute("/preview/basic-info")({
  component: () => <Form onSubmit={(data) => console.log(data)} />,
});
