// this file is generated by src/scripts/watcher.effect.ts
import Form from "@/registry/new-york/blocks/blocks";
import { createFileRoute } from "@tanstack/react-router";
export const Route = createFileRoute("/preview/blocks")({
  component: () => (
    <div className="flex min-h-screen w-full items-center justify-center py-4">
      <Form onSubmit={(data) => console.log(data)} />
    </div>
  ),
});
