// this file is generated by src/scripts/watcher.effect.ts

import { createFileRoute } from "@tanstack/react-router";
import Form from "@/components/blocks/blog-editor";
export const Route = createFileRoute("/preview/blog-editor")({
  component: () => (
    <div className="flex min-h-screen w-full items-center justify-center py-4">
      <Form onSubmit={(data) => console.log(data)} />
    </div>
  ),
});
