// this file is generated by src/scripts/watcher.effect.ts
import Form from "@/components/blocks/login";
import { createFileRoute } from "@tanstack/react-router";
export const Route = createFileRoute("/preview/login")({
  component: () => (
    <div className="flex min-h-screen w-full items-center justify-center py-4">
      <Form onSubmit={(data) => console.log(data)} />
    </div>
  ),
});
