// this file is generated by src/scripts/watcher.effect.ts
import Form from "@/registry/new-york/blocks/login";
import { createFileRoute } from "@tanstack/react-router";
export const Route = createFileRoute("/preview/login")({
  component: () => <Form onSubmit={(data) => console.log(data)} />,
});
