// this file is generated by src/scripts/watcher.effect.ts

import { createFileRoute } from "@tanstack/react-router";
import Component from "@/components/form-fields/password-input";
export const Route = createFileRoute("/preview/password-input")({
  component: () => (
    <div className="mx-auto flex min-h-screen w-11/12 max-w-3xl items-center justify-center py-4">
      <Component />
    </div>
  ),
});
