// this file is generated by src/scripts/watcher.effect.ts
import Component from "@/components/form-fields/password-input";
import { createFileRoute } from "@tanstack/react-router";
export const Route = createFileRoute("/preview/password-input")({
  component: () => (
    <div className="flex min-h-screen w-full items-center justify-center py-4">
      <Component />
    </div>
  ),
});
