// this file is generated by src/scripts/watcher.effect.ts
import Component from "@/components/form-fields/rich-text-editor";
import { createFileRoute } from "@tanstack/react-router";
export const Route = createFileRoute("/preview/rich-text-editor")({
  component: () => (
    <div className="flex min-h-screen w-full items-center justify-center py-4">
      <Component className="w-60" />
    </div>
  ),
});
