// this file is generated by src/scripts/watcher.effect.ts
import Form from "@/registry/new-york/blocks/sign-up";
import { createFileRoute } from "@tanstack/react-router";
export const Route = createFileRoute("/preview/sign-up")({
  component: () => <Form onSubmit={(data) => console.log(data)} />,
});
