/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BlocksIndexImport } from './routes/blocks/index'
import { Route as PreviewSignUpImport } from './routes/preview/sign-up'
import { Route as PreviewShippingInfoImport } from './routes/preview/shipping-info'
import { Route as PreviewLoginImport } from './routes/preview/login'
import { Route as PreviewBlocksImport } from './routes/preview/blocks'
import { Route as PreviewBasicInfoImport } from './routes/preview/basic-info'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlocksIndexRoute = BlocksIndexImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRoute,
} as any)

const PreviewSignUpRoute = PreviewSignUpImport.update({
  id: '/preview/sign-up',
  path: '/preview/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const PreviewShippingInfoRoute = PreviewShippingInfoImport.update({
  id: '/preview/shipping-info',
  path: '/preview/shipping-info',
  getParentRoute: () => rootRoute,
} as any)

const PreviewLoginRoute = PreviewLoginImport.update({
  id: '/preview/login',
  path: '/preview/login',
  getParentRoute: () => rootRoute,
} as any)

const PreviewBlocksRoute = PreviewBlocksImport.update({
  id: '/preview/blocks',
  path: '/preview/blocks',
  getParentRoute: () => rootRoute,
} as any)

const PreviewBasicInfoRoute = PreviewBasicInfoImport.update({
  id: '/preview/basic-info',
  path: '/preview/basic-info',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/preview/basic-info': {
      id: '/preview/basic-info'
      path: '/preview/basic-info'
      fullPath: '/preview/basic-info'
      preLoaderRoute: typeof PreviewBasicInfoImport
      parentRoute: typeof rootRoute
    }
    '/preview/blocks': {
      id: '/preview/blocks'
      path: '/preview/blocks'
      fullPath: '/preview/blocks'
      preLoaderRoute: typeof PreviewBlocksImport
      parentRoute: typeof rootRoute
    }
    '/preview/login': {
      id: '/preview/login'
      path: '/preview/login'
      fullPath: '/preview/login'
      preLoaderRoute: typeof PreviewLoginImport
      parentRoute: typeof rootRoute
    }
    '/preview/shipping-info': {
      id: '/preview/shipping-info'
      path: '/preview/shipping-info'
      fullPath: '/preview/shipping-info'
      preLoaderRoute: typeof PreviewShippingInfoImport
      parentRoute: typeof rootRoute
    }
    '/preview/sign-up': {
      id: '/preview/sign-up'
      path: '/preview/sign-up'
      fullPath: '/preview/sign-up'
      preLoaderRoute: typeof PreviewSignUpImport
      parentRoute: typeof rootRoute
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview/basic-info': typeof PreviewBasicInfoRoute
  '/preview/blocks': typeof PreviewBlocksRoute
  '/preview/login': typeof PreviewLoginRoute
  '/preview/shipping-info': typeof PreviewShippingInfoRoute
  '/preview/sign-up': typeof PreviewSignUpRoute
  '/blocks': typeof BlocksIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview/basic-info': typeof PreviewBasicInfoRoute
  '/preview/blocks': typeof PreviewBlocksRoute
  '/preview/login': typeof PreviewLoginRoute
  '/preview/shipping-info': typeof PreviewShippingInfoRoute
  '/preview/sign-up': typeof PreviewSignUpRoute
  '/blocks': typeof BlocksIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/preview/basic-info': typeof PreviewBasicInfoRoute
  '/preview/blocks': typeof PreviewBlocksRoute
  '/preview/login': typeof PreviewLoginRoute
  '/preview/shipping-info': typeof PreviewShippingInfoRoute
  '/preview/sign-up': typeof PreviewSignUpRoute
  '/blocks/': typeof BlocksIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview/basic-info'
    | '/preview/blocks'
    | '/preview/login'
    | '/preview/shipping-info'
    | '/preview/sign-up'
    | '/blocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview/basic-info'
    | '/preview/blocks'
    | '/preview/login'
    | '/preview/shipping-info'
    | '/preview/sign-up'
    | '/blocks'
  id:
    | '__root__'
    | '/'
    | '/preview/basic-info'
    | '/preview/blocks'
    | '/preview/login'
    | '/preview/shipping-info'
    | '/preview/sign-up'
    | '/blocks/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewBasicInfoRoute: typeof PreviewBasicInfoRoute
  PreviewBlocksRoute: typeof PreviewBlocksRoute
  PreviewLoginRoute: typeof PreviewLoginRoute
  PreviewShippingInfoRoute: typeof PreviewShippingInfoRoute
  PreviewSignUpRoute: typeof PreviewSignUpRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewBasicInfoRoute: PreviewBasicInfoRoute,
  PreviewBlocksRoute: PreviewBlocksRoute,
  PreviewLoginRoute: PreviewLoginRoute,
  PreviewShippingInfoRoute: PreviewShippingInfoRoute,
  PreviewSignUpRoute: PreviewSignUpRoute,
  BlocksIndexRoute: BlocksIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/preview/basic-info",
        "/preview/blocks",
        "/preview/login",
        "/preview/shipping-info",
        "/preview/sign-up",
        "/blocks/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/preview/basic-info": {
      "filePath": "preview/basic-info.tsx"
    },
    "/preview/blocks": {
      "filePath": "preview/blocks.tsx"
    },
    "/preview/login": {
      "filePath": "preview/login.tsx"
    },
    "/preview/shipping-info": {
      "filePath": "preview/shipping-info.tsx"
    },
    "/preview/sign-up": {
      "filePath": "preview/sign-up.tsx"
    },
    "/blocks/": {
      "filePath": "blocks/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
